-- ====================================================================
-- NEXA ORACLE DATABASE MIGRATION SCRIPT
-- FILE: 05_security_privacy_migrations.sql
-- DESCRIPTION: Forward migration for Protection Center, 2FA, Sessions,
--              Recovery Tokens, Security Events, and Privacy Settings
-- ====================================================================

-- 1. USER SECURITY SETTINGS TABLE
CREATE TABLE USER_SECURITY_SETTINGS (
    USER_ID NUMBER PRIMARY KEY,
    EMAIL_VERIFIED_AT TIMESTAMP WITH TIME ZONE,
    MFA_ENABLED NUMBER(1) DEFAULT 0 CHECK (MFA_ENABLED IN (0, 1)),
    TOTP_SECRET_CIPHERTEXT VARCHAR2(512),
    TOTP_SECRET_IV VARCHAR2(128),
    TOTP_SECRET_AUTH_TAG VARCHAR2(128),
    MFA_KEY_VERSION NUMBER DEFAULT 1,
    PASSWORD_CHANGED_AT TIMESTAMP WITH TIME ZONE,
    LAST_PROTECTION_CHECK_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SEC_SET_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 2. USER SESSIONS TABLE
CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    REFRESH_TOKEN_HASH VARCHAR2(256) NOT NULL,
    TOKEN_FAMILY_ID VARCHAR2(64) NOT NULL,
    DEVICE_NAME VARCHAR2(128),
    USER_AGENT_SUMMARY VARCHAR2(256),
    IP_HASH VARCHAR2(128),
    APPROX_CITY VARCHAR2(128),
    COUNTRY_CODE VARCHAR2(8),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    REVOKED_AT TIMESTAMP WITH TIME ZONE,
    REVOKE_REASON VARCHAR2(128),
    IS_TRUSTED NUMBER(1) DEFAULT 0 CHECK (IS_TRUSTED IN (0, 1)),
    CONSTRAINT FK_SESS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 3. MFA RECOVERY CODES TABLE
CREATE TABLE MFA_RECOVERY_CODES (
    RECOVERY_CODE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    CODE_HASH VARCHAR2(256) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    USED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_REC_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. EMAIL VERIFICATION TOKENS TABLE
CREATE TABLE EMAIL_VERIFICATION_TOKENS (
    TOKEN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOKEN_HASH VARCHAR2(256) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSUMED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_EV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 5. PASSWORD RESET TOKENS TABLE
CREATE TABLE PASSWORD_RESET_TOKENS (
    TOKEN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOKEN_HASH VARCHAR2(256) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSUMED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_PR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 6. SECURITY EVENTS AUDIT LOG TABLE
CREATE TABLE SECURITY_EVENTS (
    SECURITY_EVENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    SESSION_ID VARCHAR2(64),
    EVENT_TYPE VARCHAR2(64) NOT NULL,
    OUTCOME VARCHAR2(32) NOT NULL,
    DEVICE_SUMMARY VARCHAR2(256),
    APPROX_LOCATION VARCHAR2(128),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SECEVT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 7. USER PRIVACY SETTINGS TABLE
CREATE TABLE USER_PRIVACY_SETTINGS (
    USER_ID NUMBER PRIMARY KEY,
    IS_PRIVATE NUMBER(1) DEFAULT 0 CHECK (IS_PRIVATE IN (0, 1)),
    WHO_CAN_MESSAGE VARCHAR2(32) DEFAULT 'EVERYONE',
    WHO_CAN_COMMENT VARCHAR2(32) DEFAULT 'EVERYONE',
    ACTIVITY_STATUS_VISIBLE NUMBER(1) DEFAULT 1 CHECK (ACTIVITY_STATUS_VISIBLE IN (0, 1)),
    READ_RECEIPTS_ENABLED NUMBER(1) DEFAULT 1 CHECK (READ_RECEIPTS_ENABLED IN (0, 1)),
    HIDE_LIKE_COUNTS NUMBER(1) DEFAULT 0 CHECK (HIDE_LIKE_COUNTS IN (0, 1)),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRIV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- INDEXES FOR PERFORMANCE & FAST AUDIT QUERIES
CREATE INDEX IDX_SESS_USER_EXPIRES ON USER_SESSIONS(USER_ID, EXPIRES_AT);
CREATE INDEX IDX_SECEVT_USER_CREATED ON SECURITY_EVENTS(USER_ID, CREATED_AT DESC);
CREATE INDEX IDX_REC_USER_HASH ON MFA_RECOVERY_CODES(USER_ID, CODE_HASH);

COMMIT;
