-- Nexa Migration 06: Resumable Upload Sessions, Parts, Outbox & Processing Jobs (RERUNNABLE)

-- 1. UPLOAD_SESSIONS Table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE UPLOAD_SESSIONS (
      SESSION_ID VARCHAR2(64) PRIMARY KEY,
      USER_ID NUMBER NOT NULL,
      MEDIA_PURPOSE VARCHAR2(64) NOT NULL,
      EXPECTED_BYTES NUMBER NOT NULL,
      UPLOADED_BYTES NUMBER DEFAULT 0 NOT NULL,
      STATUS VARCHAR2(32) DEFAULT ''INITIATED'' NOT NULL,
      IDEMPOTENCY_KEY VARCHAR2(128) UNIQUE,
      EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT FK_UPLOAD_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. UPLOAD_PARTS Table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE UPLOAD_PARTS (
      SESSION_ID VARCHAR2(64) NOT NULL,
      PART_NUMBER NUMBER NOT NULL,
      BYTE_SIZE NUMBER NOT NULL,
      ETAG VARCHAR2(128),
      STATUS VARCHAR2(32) DEFAULT ''COMPLETED'' NOT NULL,
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_UPLOAD_PARTS PRIMARY KEY (SESSION_ID, PART_NUMBER),
      CONSTRAINT FK_UPART_SESSION FOREIGN KEY (SESSION_ID) REFERENCES UPLOAD_SESSIONS(SESSION_ID) ON DELETE CASCADE
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. DURABLE_OUTBOX Table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE DURABLE_OUTBOX (
      EVENT_ID VARCHAR2(64) PRIMARY KEY,
      EVENT_TYPE VARCHAR2(64) NOT NULL,
      PAYLOAD_JSON CLOB NOT NULL,
      STATUS VARCHAR2(32) DEFAULT ''PENDING'' NOT NULL,
      PROCESSED_AT TIMESTAMP WITH TIME ZONE,
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. MEDIA_PROCESSING_JOBS Table
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE MEDIA_PROCESSING_JOBS (
      JOB_ID VARCHAR2(64) PRIMARY KEY,
      USER_ID NUMBER NOT NULL,
      JOB_TYPE VARCHAR2(64) NOT NULL,
      STATUS VARCHAR2(32) DEFAULT ''QUEUED'' NOT NULL,
      PROGRESS NUMBER DEFAULT 0 NOT NULL,
      RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
      ERROR_MESSAGE VARCHAR2(1024),
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT FK_JOB_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
