-- 07_fcm_tokens_migration.sql
-- Adds Oracle persistence for user FCM push notification tokens and device registrations.
-- Safe to run repeatedly: existing tables and indexes are left unchanged.

SET SERVEROUTPUT ON;

DECLARE
  PROCEDURE create_if_missing(p_ddl VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        DBMS_OUTPUT.PUT_LINE('Object already exists; skipped.');
      ELSE
        RAISE;
      END IF;
  END;
BEGIN
  create_if_missing(q'[
    CREATE TABLE FCM_TOKENS (
      TOKEN_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      USER_ID NUMBER NOT NULL,
      TOKEN VARCHAR2(512) NOT NULL,
      PLATFORM VARCHAR2(32) DEFAULT 'android' NOT NULL,
      DEVICE_ID VARCHAR2(128),
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_FCM_TOKENS PRIMARY KEY (TOKEN_ID),
      CONSTRAINT FK_FCM_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
      CONSTRAINT UQ_FCM_TOKENS_TOKEN UNIQUE (TOKEN),
      CONSTRAINT CHK_FCM_PLATFORM CHECK (PLATFORM IN ('android', 'ios', 'web'))
    )]');

  create_if_missing('CREATE INDEX IDX_FCM_TOKENS_USER ON FCM_TOKENS (USER_ID)');
END;
/

PROMPT FCM tokens migration completed.
