-- ====================================================================
-- NEXA ORACLE DATABASE MIGRATION SCRIPT
-- FILE: 09_privacy_moderation_migrations.sql
-- DESCRIPTION: Idempotent migration for Privacy Settings, Hidden Words,
--              User Blocks, Follow Requests, Reports, and Moderation
-- ====================================================================

SET SERVEROUTPUT ON;

-- 1. ADD ROLE TO USERS IF MISSING
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (
    ROLE VARCHAR2(20) DEFAULT ''USER'' NOT NULL CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN (''USER'', ''MODERATOR'', ''ADMIN''))
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-1430, -955, -2260) THEN NULL; ELSE RAISE; END IF;
END;
/

-- 2. USER PRIVACY SETTINGS TABLE (REUSE/IDEMPOTENT)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE USER_PRIVACY_SETTINGS (
    USER_ID                 NUMBER PRIMARY KEY,
    IS_PRIVATE              NUMBER(1) DEFAULT 0 CHECK (IS_PRIVATE IN (0, 1)),
    WHO_CAN_MESSAGE         VARCHAR2(32) DEFAULT ''EVERYONE'' CHECK (WHO_CAN_MESSAGE IN (''EVERYONE'', ''FOLLOWING'', ''NOBODY'')),
    WHO_CAN_COMMENT         VARCHAR2(32) DEFAULT ''EVERYONE'' CHECK (WHO_CAN_COMMENT IN (''EVERYONE'', ''FOLLOWING'', ''NOBODY'')),
    ACTIVITY_STATUS_VISIBLE NUMBER(1) DEFAULT 1 CHECK (ACTIVITY_STATUS_VISIBLE IN (0, 1)),
    READ_RECEIPTS_ENABLED   NUMBER(1) DEFAULT 1 CHECK (READ_RECEIPTS_ENABLED IN (0, 1)),
    HIDE_LIKE_COUNTS        NUMBER(1) DEFAULT 0 CHECK (HIDE_LIKE_COUNTS IN (0, 1)),
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PRIV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 3. USER HIDDEN WORDS TABLE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE USER_HIDDEN_WORDS (
    HIDDEN_WORD_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID        NUMBER NOT NULL,
    WORD           VARCHAR2(100) NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_HW_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_HIDDEN_WORD UNIQUE (USER_ID, WORD)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_HW_USER ON USER_HIDDEN_WORDS(USER_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

-- 4. USER BLOCKS TABLE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE USER_BLOCKS (
    BLOCK_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BLOCKER_USER_ID NUMBER NOT NULL,
    BLOCKED_USER_ID NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_UB_BLOCKER FOREIGN KEY (BLOCKER_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UB_BLOCKED FOREIGN KEY (BLOCKED_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_BLOCKS UNIQUE (BLOCKER_USER_ID, BLOCKED_USER_ID),
    CONSTRAINT CHK_NO_SELF_BLOCK CHECK (BLOCKER_USER_ID <> BLOCKED_USER_ID)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_UB_BLOCKER ON USER_BLOCKS(BLOCKER_USER_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_UB_BLOCKED ON USER_BLOCKS(BLOCKED_USER_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

-- 5. FOLLOW REQUESTS TABLE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE FOLLOW_REQUESTS (
    REQUEST_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REQUESTER_USER_ID NUMBER NOT NULL,
    TARGET_USER_ID    NUMBER NOT NULL,
    STATUS            VARCHAR2(20) DEFAULT ''PENDING'' CHECK (STATUS IN (''PENDING'', ''ACCEPTED'', ''REJECTED'')),
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_FREQ_REQ FOREIGN KEY (REQUESTER_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FREQ_TGT FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_FOLLOW_REQUEST UNIQUE (REQUESTER_USER_ID, TARGET_USER_ID),
    CONSTRAINT CHK_NO_SELF_FREQ CHECK (REQUESTER_USER_ID <> TARGET_USER_ID)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_FREQ_TGT_STATUS ON FOLLOW_REQUESTS(TARGET_USER_ID, STATUS)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

-- 6. USER REPORTS TABLE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE USER_REPORTS (
    REPORT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REPORTER_USER_ID NUMBER NOT NULL,
    TARGET_TYPE      VARCHAR2(30) NOT NULL CHECK (TARGET_TYPE IN (''USER'', ''POST'', ''COMMENT'', ''STORY'', ''REEL'', ''MESSAGE'')),
    TARGET_ID        NUMBER NOT NULL,
    REASON           VARCHAR2(60) NOT NULL,
    DETAILS          VARCHAR2(1000),
    STATUS           VARCHAR2(30) DEFAULT ''PENDING'' CHECK (STATUS IN (''PENDING'', ''INVESTIGATING'', ''RESOLVED'', ''DISMISSED'')),
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_REP_USER FOREIGN KEY (REPORTER_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_REP_STATUS_CREATED ON USER_REPORTS(STATUS, CREATED_AT DESC)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_REP_TARGET ON USER_REPORTS(TARGET_TYPE, TARGET_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

-- 7. MODERATION ACTIONS TABLE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE MODERATION_ACTIONS (
    ACTION_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REPORT_ID          NUMBER,
    MODERATOR_USER_ID  NUMBER NOT NULL,
    ACTION_TYPE        VARCHAR2(50) NOT NULL CHECK (ACTION_TYPE IN (''WARN'', ''HIDE_CONTENT'', ''DELETE_CONTENT'', ''SUSPEND_USER'', ''BAN_USER'', ''DISMISS_REPORT'')),
    TARGET_TYPE        VARCHAR2(30) NOT NULL,
    TARGET_ID          NUMBER NOT NULL,
    NOTES              VARCHAR2(1000),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MOD_REP FOREIGN KEY (REPORT_ID) REFERENCES USER_REPORTS(REPORT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_MOD_USER FOREIGN KEY (MODERATOR_USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_MOD_MODERATOR ON MODERATION_ACTIONS(MODERATOR_USER_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_MOD_TARGET ON MODERATION_ACTIONS(TARGET_TYPE, TARGET_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/

COMMIT;
