-- ====================================================================
-- NEXA ORACLE DATABASE MIGRATION SCRIPT
-- FILE: 10_email_otp_2fa.sql
-- DESCRIPTION: Idempotent email OTP challenge storage for login 2FA
-- ====================================================================
SET SERVEROUTPUT ON;
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE LOGIN_OTP_CHALLENGES (
    CHALLENGE_ID VARCHAR2(64) PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    OTP_HASH VARCHAR2(64) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ATTEMPTS NUMBER(2) DEFAULT 0 NOT NULL,
    CONSUMED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_LOGIN_OTP_USER
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CK_LOGIN_OTP_ATTEMPTS
      CHECK (ATTEMPTS BETWEEN 0 AND 5)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LOGIN_OTP_USER
    ON LOGIN_OTP_CHALLENGES(USER_ID, CREATED_AT)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
END;
/
COMMIT;