-- ====================================================================
-- NEXA ORACLE DATABASE SCHEMA MIGRATION
-- FILE: database/18_message_interactions.sql
-- DESCRIPTION: Message Interactions Phase — Reactions, Edit, Reply
--              Adds MESSAGE_REACTIONS table, edited_at and
--              reply_to_message_id to MESSAGES and GROUP_MESSAGES.
-- TARGETS: Oracle Database 19c/21c
-- SAFE: All operations are ADDITIVE. No destructive changes.
--       Wrapped in BEGIN/EXCEPTION so re-running is idempotent.
-- ====================================================================

-- ----------------------------------------------------------------
-- 1. Add REPLY_TO_MESSAGE_ID to MESSAGES (DMs)
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE MESSAGES
    ADD REPLY_TO_MESSAGE_ID NUMBER
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF; -- ORA-01430: column already exists
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE MESSAGES
    ADD CONSTRAINT FK_MSG_REPLY_TO
      FOREIGN KEY (REPLY_TO_MESSAGE_ID)
      REFERENCES MESSAGES(MESSAGE_ID)
      ON DELETE SET NULL
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2264 THEN RAISE; END IF; -- ORA-02264: name already in use
END;
/

-- ----------------------------------------------------------------
-- 2. Add EDITED_AT to MESSAGES (DMs)
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE MESSAGES
    ADD EDITED_AT TIMESTAMP WITH TIME ZONE
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------
-- 3. Add REPLY_TO_MESSAGE_ID to GROUP_MESSAGES
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE GROUP_MESSAGES
    ADD REPLY_TO_MESSAGE_ID NUMBER
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE GROUP_MESSAGES
    ADD CONSTRAINT FK_GRP_MSG_REPLY_TO
      FOREIGN KEY (REPLY_TO_MESSAGE_ID)
      REFERENCES GROUP_MESSAGES(MESSAGE_ID)
      ON DELETE SET NULL
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------
-- 4. Add EDITED_AT to GROUP_MESSAGES
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE GROUP_MESSAGES
    ADD EDITED_AT TIMESTAMP WITH TIME ZONE
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------
-- 5. Add IS_UNSENT to GROUP_MESSAGES (parity with MESSAGES)
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE GROUP_MESSAGES
    ADD IS_UNSENT NUMBER(1) DEFAULT 0 NOT NULL
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------
-- 6. Create MESSAGE_REACTIONS table
--    Exactly one of MESSAGE_ID or GROUP_MESSAGE_ID must be set.
--    Unique constraint: one reaction per user per message.
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE MESSAGE_REACTIONS (
      REACTION_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      MESSAGE_ID          NUMBER,
      GROUP_MESSAGE_ID    NUMBER,
      USER_ID             NUMBER NOT NULL,
      REACTION            VARCHAR2(10) NOT NULL,
      CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,

      CONSTRAINT FK_REACTION_MSG
        FOREIGN KEY (MESSAGE_ID)
        REFERENCES MESSAGES(MESSAGE_ID) ON DELETE CASCADE,

      CONSTRAINT FK_REACTION_GRP_MSG
        FOREIGN KEY (GROUP_MESSAGE_ID)
        REFERENCES GROUP_MESSAGES(MESSAGE_ID) ON DELETE CASCADE,

      CONSTRAINT FK_REACTION_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,

      -- Exactly one destination
      CONSTRAINT CHK_REACTION_DEST CHECK (
        (MESSAGE_ID IS NOT NULL AND GROUP_MESSAGE_ID IS NULL) OR
        (MESSAGE_ID IS NULL AND GROUP_MESSAGE_ID IS NOT NULL)
      ),

      -- One active reaction per user per DM message
      CONSTRAINT UQ_REACTION_DM UNIQUE (MESSAGE_ID, USER_ID),

      -- One active reaction per user per group message
      CONSTRAINT UQ_REACTION_GRP UNIQUE (GROUP_MESSAGE_ID, USER_ID)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; -- ORA-00955: name already used
END;
/

-- Indexes for query performance
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_REACTIONS_MSG_ID ON MESSAGE_REACTIONS (MESSAGE_ID) WHERE MESSAGE_ID IS NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_REACTIONS_GRP_MSG_ID ON MESSAGE_REACTIONS (GROUP_MESSAGE_ID) WHERE GROUP_MESSAGE_ID IS NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_REACTIONS_USER_ID ON MESSAGE_REACTIONS (USER_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------
-- 7. Indexes on new columns for performance
-- ----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_MSG_REPLY_TO ON MESSAGES (REPLY_TO_MESSAGE_ID) WHERE REPLY_TO_MESSAGE_ID IS NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_GRP_MSG_REPLY_TO ON GROUP_MESSAGES (REPLY_TO_MESSAGE_ID) WHERE REPLY_TO_MESSAGE_ID IS NOT NULL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
