-- Nexa Database Verification & Audit Script (SELECT-ONLY)

-- 1. Active Users Count & Verification
SELECT USER_ID, USERNAME, EMAIL, DISPLAY_NAME, CREATED_AT 
FROM USERS 
ORDER BY CREATED_AT DESC;

-- 2. Follower Relationships Count
SELECT FOLLOWER_ID, FOLLOWING_ID, CREATED_AT 
FROM FOLLOWERS;

-- 3. Posts & Media Assets
SELECT POST_ID, USER_ID, CONTENT, IMAGE_URL, CREATED_AT 
FROM POSTS 
ORDER BY CREATED_AT DESC;

-- 4. Stories & Expiration
SELECT STORY_ID, USER_ID, MEDIA_URL, CREATED_AT, EXPIRES_AT 
FROM STORIES 
WHERE EXPIRES_AT > SYSTIMESTAMP 
ORDER BY CREATED_AT DESC;

-- 5. Reels Video Content
SELECT r.REEL_ID, r.USER_ID, r.VIDEO_URL, r.CAPTION,
       (SELECT COUNT(*) FROM REEL_LIKES rl WHERE rl.REEL_ID = r.REEL_ID) AS LIKES_COUNT,
       r.CREATED_AT
FROM REELS r
ORDER BY CREATED_AT DESC;

-- 5b. Persisted media metadata
SELECT ASSET_ID, USER_ID, STORAGE_KEY, MIME_TYPE, SIZE_BYTES, MEDIA_KIND, CREATED_AT
FROM MEDIA_ASSETS
ORDER BY CREATED_AT DESC;

-- 6. Direct Messages
SELECT MESSAGE_ID, SENDER_ID, RECEIVER_ID, CONTENT, READ_AT, CREATED_AT 
FROM MESSAGES 
ORDER BY CREATED_AT DESC;

-- 7. Active & Revoked Sessions
SELECT SESSION_ID, USER_ID, DEVICE_NAME, LAST_SEEN_AT, REVOKED_AT 
FROM USER_SESSIONS 
ORDER BY LAST_SEEN_AT DESC;

-- 8. Security Settings & 2FA Status
SELECT USER_ID, EMAIL_VERIFIED_AT, MFA_ENABLED, LAST_PROTECTION_CHECK_AT 
FROM USER_SECURITY_SETTINGS;
