import React from 'react';
import { Bot, User, Copy, Check } from 'lucide-react';
import { AiMessage } from '../../api/ai.api.js';
import { Avatar } from '../ui/Avatar.js';
import { useAuth } from '../../contexts/AuthContext.js';
import { formatDistanceToNow } from 'date-fns';

interface AiMessageBubbleProps {
  message: {
    messageId?: number;
    role: 'user' | 'assistant' | 'system';
    content: string;
    createdAt?: string;
    isStreaming?: boolean;
  };
}

export const AiMessageBubble: React.FC<AiMessageBubbleProps> = ({ message }) => {
  const { user } = useAuth();
  const [copied, setCopied] = React.useState(false);

  const isUser = message.role === 'user';

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  };

  const formattedTime = message.createdAt
    ? formatDistanceToNow(new Date(message.createdAt), { addSuffix: true })
    : 'Just now';

  return (
    <div className={`flex gap-3 group ${isUser ? 'flex-row-reverse' : 'flex-row'} items-start w-full`}>
      {/* Avatar Indicator */}
      {isUser ? (
        <Avatar
          src={user?.profileImageUrl}
          name={user?.displayName || user?.username || 'You'}
          size="sm"
          className="mt-1 flex-shrink-0"
        />
      ) : (
        <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-brand-600 via-indigo-500 to-aurora-cyan p-0.5 mt-1 flex-shrink-0 flex items-center justify-center shadow-glow-brand ring-2 ring-brand-500/30">
          <div className="w-full h-full bg-background-card/90 rounded-full flex items-center justify-center">
            <Bot className="w-4 h-4 text-aurora-cyan animate-pulse-slow" />
          </div>
        </div>
      )}

      {/* Bubble Container */}
      <div className={`flex flex-col max-w-[85%] sm:max-w-[75%] ${isUser ? 'items-end' : 'items-start'}`}>
        <div className="flex items-center gap-2 mb-1 px-1">
          <span className="text-[11px] font-semibold text-slate-400">
            {isUser ? (user?.displayName || user?.username || 'You') : 'NEXA AI'}
          </span>
          <span className="text-[10px] text-slate-500">{formattedTime}</span>
        </div>

        <div
          className={`relative px-4 py-3 rounded-2xl text-xs sm:text-sm leading-relaxed transition-all whitespace-pre-wrap break-words ${
            isUser
              ? 'bg-gradient-to-r from-brand-600 to-indigo-600 text-white rounded-tr-none shadow-md shadow-brand-900/30'
              : 'bg-background-card/90 text-slate-100 border border-slate-800/90 rounded-tl-none shadow-lg backdrop-blur-md'
          }`}
        >
          {message.content}

          {/* Streaming blinking cursor */}
          {message.isStreaming && (
            <span className="inline-block w-2 h-4 ml-1 bg-aurora-cyan animate-pulse align-middle" />
          )}

          {/* Copy Button for Assistant responses */}
          {!isUser && !message.isStreaming && message.content && (
            <div className="mt-2 pt-2 border-t border-slate-800/60 flex items-center justify-between text-slate-400 text-xs">
              <span className="text-[10px] text-slate-500">✨ Generated by NEXA AI</span>
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-1 hover:text-aurora-cyan text-[11px] transition-colors px-1.5 py-0.5 rounded hover:bg-slate-800/50"
                title="Copy message"
                aria-label="Copy message"
              >
                {copied ? (
                  <>
                    <Check className="w-3 h-3 text-emerald-400" />
                    <span className="text-emerald-400">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3 h-3" />
                    <span>Copy</span>
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
